# Generated by Django 5.2.7 on 2025-11-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('lorenz', 'Lorenz Attractor'), ('henon', 'Henon Map'), ('thomas', 'Thomas Attractor')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_params', models.JSONField()),
                ('results', models.JSONField()),
                ('is_stable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
